baseURL = 'https://geniexr.art/blog/'
languageCode = 'en-us'
title = 'Dialectical Culture'
theme = 'hugo-swift-theme'
author = "Daylan Nance"
copyright = "This blog's copyright was established when Churck Norris round house kicked a T-Rex, and will last until he decides to punch a black hole into oblivion. Copyright ¬© Daylan Nance, Jurassic Era - End of Time, all rights reserved."
canonifyurls = true
paginate = 4
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
 # [params.designer]
 #   name = "Weru"
 #   url = "https://www.linkedin.com/in/dan-weru-profile/"
  [[params.authors]]
    name = "Daylan" # can be nickname # if fullName üëáüèª isn't set, name will be displayed on author card
    fullName = "Daylan Nance" # optional. If set, it will display on author card
    bio = "I'm Daylan, I got iDARES!"
    photo = "myPhotoFile.jpg"
   # url = "https://myURLofChoice.domain"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # logo = "logo.png"
  # author = "Weru" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>
#[taxonomies]
#  category = "categories"


[menu]
 # [[menu.main]]
 #   name = "About"
 #   url = "about/"
 #   weight = 2
  [[menu.main]]
    name = "UAP"
    url = "categories/uap/"
    weight = 4
  [[menu.main]]
    name = "AI"
    url = "categories/ai/"
    weight = 5
  [[menu.main]]
    name = "Physics"
    url = "categories/physics/"
    weight = 6
  [[menu.main]]
    name = "Dev"
    url = "categories/dev/"
    weight = 7
  [[menu.main]]
    name = "Politics"
    url = "categories/politics/"

  [[menu.main]]
    name = "Philosophy"
    url = "categories/philosophy/"
    weight = 9
  [[menu.main]]
    name = "Consciousness"
    url = "categories/consciousness/"
    weight = 9

